// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Decrypt(arg1:string,arg2:string):Promise<string>;

export function DownloadAttachment(arg1:number,arg2:string,arg3:string):Promise<string>;

export function Encrypt(arg1:string,arg2:Array<number>):Promise<string>;

export function FetchEmails(arg1:number,arg2:string):Promise<Array<main.Email>>;

export function GenRand(arg1:string):Promise<Array<number>>;

export function PickFiles():Promise<Array<string>>;

export function ReadEmail(arg1:number,arg2:string):Promise<main.FullEmail>;

export function SendEmail(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>,arg7:string):Promise<string>;

export function SignIn():Promise<string>;

export function ToggleRead(arg1:number,arg2:boolean):Promise<string>;

export function ToggleStarred(arg1:number,arg2:boolean):Promise<string>;
