// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchEmails(arg1) {
  return window['go']['main']['App']['FetchEmails'](arg1);
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function SendEmail(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SendEmail'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ToggleRead(arg1, arg2) {
  return window['go']['main']['App']['ToggleRead'](arg1, arg2);
}

export function ToggleStarred(arg1, arg2) {
  return window['go']['main']['App']['ToggleStarred'](arg1, arg2);
}
